{
 "title": "ESP32 State & Data",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_id",
    "query": "from(bucket: \"esp32data\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"esp32\")\r\n|> group(columns: [\"device_id\"])\r\n|> map(fn: (r) => ({ device_id: r.device_id }))"
   }
  ]
 },
 "panels": [
  { "title": "Device stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "device_id" },
  {
   "title": "Number of data points",
   "type": "bargauge",
   "description": "Number of data points in database for device in the selected time range.",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"esp32state\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"esp32\")\r\n  |> group(columns: [\"device_id\"])\r\n  |> count()\r\n  |> yield(name: \"count\")\r\n  |> map(fn: (r) => ({ device_id: r.device_id }))\r\n"
    }
   ]
  },
  {
   "title": "Current LED state",
   "type": "stat",
   "description": "Color of the current LED state for device.",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"esp32state\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"esp32\")\r\n|> filter(fn: (r) => r.device_id == \"${device_id}\")\r\n|> map(fn: (r) => ({ color: r._value, time: r._time }))"
    }
   ]
  },
  {
   "title": "LED states over time",
   "type": "state-timeline",
   "description": "A graph showing different states of LED through time.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"esp32state\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"esp32\")\r\n|> filter(fn: (r) => r.device_id == \"${device_id}\")\r\n|> map(fn: (r) => ({ color: r._value, time: r._time }))"
    }
   ]
  },
  { "title": "Monitored data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Current temperature",
   "type": "stat",
   "description": "Current temperature measured by DHT11.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"esp32data\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"esp32\" and r._field == \"temperature\")\r\n|> filter(fn: (r) => r.device_id == \"${device_id}\")\r\n|> group(columns: [\"device_id\"])\r\n|> keep(columns: [\"_time\", \"_value\", \"device_id\"])"
    }
   ]
  },
  {
   "title": "Current humidity",
   "type": "stat",
   "description": "Current air humidity measured by DHT11.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"esp32data\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"esp32\" and r._field == \"humidity\")\r\n|> filter(fn: (r) => r.device_id == \"${device_id}\")\r\n|> group(columns: [\"device_id\"])\r\n|> keep(columns: [\"_time\", \"_value\", \"device_id\"])"
    }
   ]
  },
  {
   "title": "Current moisture",
   "type": "stat",
   "description": "Current soil moisture measured by VMA303.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"esp32data\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"esp32\" and r._field == \"moisture\")\r\n|> filter(fn: (r) => r.device_id == \"${device_id}\")\r\n|> group(columns: [\"device_id\"])\r\n|> keep(columns: [\"_time\", \"_value\", \"device_id\"])"
    }
   ]
  },
  {
   "title": "Temperature over time",
   "type": "timeseries",
   "description": "Temperature measured by DHT11 over time.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"esp32data\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"esp32\" and r._field == \"temperature\")\r\n|> filter(fn: (r) => r.device_id == \"${device_id}\")\r\n|> group(columns: [\"device_id\"])\r\n|> keep(columns: [\"_time\", \"_value\", \"device_id\"])"
    }
   ]
  },
  {
   "title": "Humidity over time",
   "type": "timeseries",
   "description": "Air humidity measured by DHT11 over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"esp32data\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"esp32\" and r._field == \"humidity\")\r\n|> filter(fn: (r) => r.device_id == \"${device_id}\")\r\n|> group(columns: [\"device_id\"])\r\n|> keep(columns: [\"_time\", \"_value\", \"device_id\"])"
    }
   ]
  },
  {
   "title": "Moisture over time",
   "type": "timeseries",
   "description": "Soil moisture measured by VMA303 over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"esp32data\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"esp32\" and r._field == \"moisture\")\r\n|> filter(fn: (r) => r.device_id == \"${device_id}\")\r\n|> group(columns: [\"device_id\"])\r\n|> keep(columns: [\"_time\", \"_value\", \"device_id\"])"
    }
   ]
  }
 ]
}